// <auto-generated />
using System;
using Gah.Blocks.CqrsEs.EventStore.Sql.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gah.Patterns.ToDo.Api.Data.Migrations.EventStore
{
    [DbContext(typeof(EventStoreDbContext))]
    [Migration("20190313003629_InitialEventStoreDbMigration")]
    partial class InitialEventStoreDbMigration
    {
        /// <summary>
        /// Implemented to builds the <see cref="P:Microsoft.EntityFrameworkCore.Migrations.Migration.TargetModel" />.
        /// </summary>
        /// <param name="modelBuilder">The <see cref="T:Microsoft.EntityFrameworkCore.ModelBuilder" /> to use to build the model.</param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gah.Blocks.CqrsEs.EventStore.Sql.Entities.EventSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Event")
                        .IsRequired();

                    b.Property<long>("EventNumber");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.HasAlternateKey("Stream", "EventNumber");

                    b.ToTable("ES_EventStore");
                });
#pragma warning restore 612, 618
        }
    }
}
