// <auto-generated />
using System;
using Gah.Blocks.CqrsEs.EventStore.Sql.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gah.Patterns.ToDo.Api.Data.Migrations.EventStore
{
    [DbContext(typeof(EventStoreDbContext))]
    partial class EventStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gah.Blocks.CqrsEs.EventStore.Sql.Entities.EventSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Event")
                        .IsRequired();

                    b.Property<long>("EventNumber");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.HasAlternateKey("Stream", "EventNumber");

                    b.ToTable("ES_EventStore");
                });
#pragma warning restore 612, 618
        }
    }
}
